/**
 * Vedic AI Copilot Engine v5.0 — Full Hybrid AI Core
 * NLP (Regex+Python) + Swiss Ephemeris + Rule Engine + NLG
 * Zero external LLM dependency.
 */

const aiCore = require('../ai_core/index');
const logger = require('./logger');

async function processChatRequest(userMessage, city, date, birthDetails, panchangData, fetchmuhurat, createBharagvTable, history = [], sessionId = null, onStatus = null) {
  try {
    logger.info({ message: '[ChatEngine] Processing via internal AI Core v5.0', query: userMessage });

    const contextParams = {
      city,
      date,
      userProfile: birthDetails || {},
      panchang: panchangData || {},
      rawPanchang: panchangData || {}, // Full raw panchang for NLG and rules
      history: history,
      sessionId, // Enable session memory across turns
    };

    const result = await aiCore.processQuery(userMessage, contextParams, onStatus);

    if (result.success && result.response) {
      const text = result.response.text || result.response.markdown || '';
      return {
        success: true,
        intent: result.intents?.map(i => i.intent).join('+') || 'AI_CORE',
        formattedResponse: text || 'I processed your request but could not generate a clear response.',
        model: 'vedic-ai-core-v5',
        meta: result.meta || {},
        context: result.context,
      };
    } else if (!result.success && result.response) {
      // Return the actual error message generated by AI Core
      return {
        success: false,
        intent: 'ERROR',
        formattedResponse: result.response.text || 'An internal error occurred during processing.',
        model: 'vedic-ai-core-v5',
        errorDetails: result.details
      };
    }

    return {
      success: true,
      intent: 'UNCLEAR',
      formattedResponse: '🕉️ I could not fully understand that query. Try asking about your **Lagna**, **Nakshatra**, **travel**, or **best business time** today.',
      model: 'vedic-ai-core-v5',
    };

  } catch (error) {
    logger.error({ message: '[ChatEngine] AI Core error', error: error.message });
    return {
      success: true,
      intent: 'ERROR',
      formattedResponse: '⚠️ A calculation error occurred. Please try again or rephrase your question.',
      model: 'vedic-ai-core-v5',
    };
  }
}

module.exports = { processChatRequest, parseUserQuery: () => ({}) };

